name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Build
        run: |
          # 1. Установка системных библиотек
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
          # 2. Установка Buildozer и Cython
          pip3 install --user --upgrade Cython==0.29.33 wheel buildozer
          export PATH=$PATH:$HOME/.local/bin
          
          # 3. ЗАПУСК СБОРКИ (Самый важный этап)
          # Мы используем 'yes |', чтобы автоматически соглашаться на все лицензии Android SDK
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-bundle
          path: bin/*.apk
          
